//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLiteModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductReport
    {
        public long ProductReportID { get; set; }
        public string ProductName { get; set; }
        public string VendorName { get; set; }
        public Nullable<decimal> TotalQuantitySold { get; set; }
        public Nullable<decimal> TotalIncomes { get; set; }
        public Nullable<int> ProductID { get; set; }
    }
}
